### ISSUE TITLE
Failed building wheels for pymetis

### ISSUE THREAD

**Issue by MojGGG** [inducer/pymetis#11]
Hi,

I am truning to install pymetis on windows using pip install pymetis command. However, I am getting an error about failing building the whell. Could you please help me how I address this problem? Is the problem related to gcc?
Thanks

**Comment by inducer** [comment]
Could you paste the output from the installation? Does the package work after installation, despite the wheel message? (run the tests)

**Comment by MojGGG** [comment]
Building wheels for collected packages: pymetis
  Building wheel for pymetis (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\GoftariM\AppData\Local\Continuum\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GoftariM\\AppData\\Local\\Temp\\pip-install-a7c2h96v\\pymetis\\setup.py'"'"'; __file__='"'"'C:\\Users\\GoftariM\\AppData\\Local\\Temp\\pip-install-a7c2h96v\\pymetis\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\GoftariM\AppData\Local\Temp\pip-wheel-8_qeiknv' --python-tag cp37
       cwd: C:\Users\GoftariM\AppData\Local\Temp\pip-install-a7c2h96v\pymetis\
  Complete output (22 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\pymetis
  copying pymetis\version.py -> build\lib.win-amd64-3.7\pymetis
  copying pymetis\__init__.py -> build\lib.win-amd64-3.7\pymetis
  running build_clib
  building 'metis' library
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\src
  creating build\temp.win-amd64-3.7\src\metis
  creating build\temp.win-amd64-3.7\src\metis\GKlib
  creating build\temp.win-amd64-3.7\src\metis\libmetis
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Isrc/metis/GKlib -Isrc/metis/include -Isrc/metis/libmetis "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/metis/GKlib\b64.c /Fobuild\temp.win-amd64-3.7\src/metis/GKlib\b64.obj
  b64.c
  C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_math.h(90): warning C4005: 'INFINITY': macro redefinition
  C:\Users\GoftariM\AppData\Local\Temp\pip-install-a7c2h96v\pymetis\src\metis\GKlib\gk_arch.h(67): note: see previous definition of 'INFINITY'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_math.h(532): error C2059: syntax error: '('
  C:\Users\GoftariM\AppData\Local\Temp\pip-install-a7c2h96v\pymetis\src\metis\GKlib\GKlib.h(51): fatal error C1083: Cannot open include file: 'regex.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pymetis
  Running setup.py clean for pymetis
Failed to build pymetis
Installing collected packages: pymetis
  Running setup.py install for pymetis ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\GoftariM\AppData\Local\Continuum\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GoftariM\\AppData\\Local\\Temp\\pip-install-a7c2h96v\\pymetis\\setup.py'"'"'; __file__='"'"'C:\\Users\\GoftariM\\AppData\\Local\\Temp\\pip-install-a7c2h96v\\pymetis\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GoftariM\AppData\Local\Temp\pip-record-zcxye4wo\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\GoftariM\AppData\Local\Temp\pip-install-a7c2h96v\pymetis\
    Complete output (22 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\pymetis
    copying pymetis\version.py -> build\lib.win-amd64-3.7\pymetis
    copying pymetis\__init__.py -> build\lib.win-amd64-3.7\pymetis
    running build_clib
    building 'metis' library
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\src
    creating build\temp.win-amd64-3.7\src\metis
    creating build\temp.win-amd64-3.7\src\metis\GKlib
    creating build\temp.win-amd64-3.7\src\metis\libmetis
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Isrc/metis/GKlib -Isrc/metis/include -Isrc/metis/libmetis "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/metis/GKlib\b64.c /Fobuild\temp.win-amd64-3.7\src/metis/GKlib\b64.obj
    b64.c
    C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_math.h(90): warning C4005: 'INFINITY': macro redefinition
    C:\Users\GoftariM\AppData\Local\Temp\pip-install-a7c2h96v\pymetis\src\metis\GKlib\gk_arch.h(67): note: see previous definition of 'INFINITY'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_math.h(532): error C2059: syntax error: '('    C:\Users\GoftariM\AppData\Local\Temp\pip-install-a7c2h96v\pymetis\src\metis\GKlib\GKlib.h(51): fatal error C1083: Cannot open include file: 'regex.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\GoftariM\AppData\Local\Continuum\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GoftariM\\AppData\\Local\\Temp\\pip-install-a7c2h96v\\pymetis\\setup.py'"'"'; __file__='"'"'C:\\Users\\GoftariM\\AppData\\Local\\Temp\\pip-install-a7c2h96v\\pymetis\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GoftariM\AppData\Local\Temp\pip-record-zcxye4wo\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by inducer** [comment]
Pymetis does not support Windows.

**Comment by MojGGG** [comment]
Thanks. Does it support Linux?

**Comment by inducer** [comment]
Yes.

**Comment by Gxming2024** [comment]
> Yes.

Does it still not support  windows?

**Comment by inducer** [comment]
It does not. You could volunteer to maintain the Windows wheel.
