### ISSUE TITLE
Graph with starting index 1 

### ISSUE THREAD

**Issue by mrjoelc** [inducer/pymetis#23]
Hi,

I'm using this wrapper as the little "tutorial" explain, but when I pass my graph (about 5000 nodes) with starting index not 0 but 1 it gives as cut : -66. So I think the problem is with the index not being 0 but 1.

Any help?

**Comment by inducer** [comment]
Are you reporting something you think is a bug in pymetis? If not, you're in the wrong spot. If so, you should supply a self-contained MWE. Changing a graph to have zero-based vertex indices should be easy, if that's what your issue is.

**Comment by mrjoelc** [comment]
Sorry, my mistake!
It's my first attempt with graph. 
All I need to do is subtract 1 to all the numbers that rappresents edges when I read the file of graph.

Anyway, thanks for your work!
