### ISSUE TITLE
where can i find the definition of 'iset' function?

### ISSUE THREAD

**Issue by 01team** [inducer/pymetis#34]
<img width="648" alt="截屏2021-07-16 下午7 03 17" src="https://user-images.githubusercontent.com/67887180/125938174-1e698f06-a14a-4a5c-8cc2-b504c2679202.png">

**Comment by inducer** [comment]
It looks like you're asking about details of metis, not pymetis. Please ask in the appropriate place, see http://glaros.dtc.umn.edu/.
