### ISSUE TITLE
Have a trouble with 'contiguous' option

### ISSUE THREAD

**Issue by microhumanis** [inducer/pymetis#41]
### Discussed in https://github.com/inducer/pymetis/discussions/40

<div type='discussions-op-text'>

<sup>Originally posted by **microhumanis** July 19, 2022</sup>
Hi, while I am using the 'part_graph' command to divide graph into contiguous partitions, I faced a error 'TypeError: part_graph() got an unexpected keyword argument 'contiguous'' 

How can I handle this problem?

Thank you :) 
</div>

**Comment by inducer** [comment]
Insufficient detail to reproduce. Unlikely to be an actual issue.

Also, please be considerate of open source maintainers: Why cause more work by spamming things as issues and discussions, particularly when it's likely that the issue is on your end?
