### ISSUE TITLE
PyMetis not building on 10.14.5

### ISSUE THREAD

**Issue by zbskii** [inducer/pymetis#9]
clang builds fail:

`clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -fwrapv -Wall -O3 -DNDEBUG -DHAVE_MREMAP=0 -Isrc/metis/GKlib -Isrc/metis/include -Isrc/metis/libmetis -I/usr/local/include/python3.7m -I/Users/bcarter/Library/Python/3.7/include/python3.7m -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/wrapper/wrapper.cpp -o build/temp.macosx-10.14-x86_64-3.7/src/wrapper/wrapper.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="2019.1" -std=c++14 -fvisibility=hidden
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -fwrapv -Wall -O3 -DNDEBUG -DHAVE_MREMAP=0 -Isrc/metis/GKlib -Isrc/metis/include -Isrc/metis/libmetis -I/usr/local/include/python3.7m -I/Users/bcarter/Library/Python/3.7/include/python3.7m -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/metis/GKlib/htable.c -o build/temp.macosx-10.14-x86_64-3.7/src/metis/GKlib/htable.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="2019.1" -std=c++14 -fvisibility=hidden
error: invalid argument '-std=c++14' not allowed with 'C'
error: command 'clang' failed with exit status 1`

`$ clang -v
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

**Comment by inducer** [comment]
I'm assuming you are using 2019.1 from the package index. Try the new 2019.1.1 which I've just released. Reopen this if the issue persists.

**Comment by zbskii** [comment]
Works great, thank you!
